{
 "title": "Kafka Cluster / Global HealthCheck",
 "tags": [
  "kafka",
  "broker",
  "healthcheck"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values(kafka_server_brokerstate, env)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "custom_request_duration" }
   ]
  },
  {
   "title": "Bytes Out per sec",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 10, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(kafka_server_broker_topic_metrics_bytesoutpersec_rate{topic=\"\"}) by (broker)"
    }
   ]
  },
  {
   "title": "Bytes In per sec",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(kafka_server_broker_topic_metrics_bytesinpersec_rate{topic=\"\"}) by (broker)"
    }
   ]
  },
  {
   "title": "Brokers Running(>=3)",
   "type": "stat",
   "description": "Total number of brokers with a state running (i.e 3)",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((kafka_server_brokerstate{env=\"$env\"}) == 3 or (kafka_server_brokerstate{env=\"$env\"}) == 4)"
    }
   ]
  },
  {
   "title": "Active Controller",
   "type": "stat",
   "description": "Number of active controllers in the cluster. Alert if the aggregated sum across all brokers in the cluster is anything other than 1 because there should be exactly one controller per cluster.",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_activecontrollercount{env=\"$env\"})"
    }
   ]
  }
 ]
}